apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: godemo-dev
  POSTGRES_PASSWORD: godemo-dev
  POSTGRES_DB: godemo-dev
  DATABASE_URL: postgresql://godemo-dev:godemo-dev@godemo-dev-rw.godemo-dev.svc.cluster.local:5432/godemo-dev?sslmode=disable
