apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: laravel-app
  namespace: fleet-local
spec:
  repo: https://github.com/Alexuresp/godemo
  branch: main
  paths:
    - fleet/laravel-app
