apiVersion: v1
kind: Secret
metadata:
  name: laravel
  labels:
    app: laravel
type: Opaque
stringData:
  APP_KEY: base64:2kL9vN3mQ7wX5zA1bC8dE6fG0hJ2kL9vN3mQ7wX5zA1bC8dE6fG0hJ2kL9v=
  DB_PASSWORD: laravel
