apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: godemo
type: Opaque
stringData:
  MINIO_ACCESS_KEY: admin
  MINIO_SECRET_KEY: super-secret-password
  MINIO_HOST: 10.132.7.1
  MINIO_PORT: "9000"
