apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: godemo
  POSTGRES_PASSWORD: godemo
  POSTGRES_DB: godemo
  DATABASE_URL: postgresql://godemo:godemo@godemo-rw.godemo.svc.cluster.local:5432/godemo?sslmode=disable
