apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-credentials
  labels:
    app: pg-backup
type: Opaque
stringData:
  GODEMO_PASSWORD: godemo
  GODEMO_DEV_PASSWORD: godemo-dev
  LARAVEL_PASSWORD: laravel
